export const MAIN = "http://172.17.3.123:5000"
export const LOGIN = MAIN + "/auth/login"
export const SIGNUP = MAIN + "/auth/registeration"
export const PICKSQUAD = MAIN + "/team/pick-squad"
export const MANAGE_TEAM = MAIN + "/team/my-team";
export const GET_TRANSFERABLE = MAIN + "/team/pick-squad";
export const POST_TRANSFERABLE = MAIN + "/team/my-team/transfer";
export const CLUBS = MAIN + "/club/2021/clubs"
export const PLAYERS = MAIN + "/player/2021/pick-squad";
export const COMPETITIONS = MAIN + "/competition/list";
export const INFORMATION = MAIN + "/user/profile";
export const EDIT_PROFILE = MAIN + "/user/account";