export const auth_action_types = {
    LOGIN_SUCCESS : 'LOGIN_SUCCESS',
    LOGIN_FAILURE : 'LOGIN_FAILURE',
    LOGOUT_SUCCESS : 'LOGOUT_SUCCESS'
  }
export const picksquad_action_types = {
    SET_PLAYERS_SUCCESS : 'SET_PLAYERS_SUCCESS'
  }

export const search_action_types = {
    GET_PLAYERS_SUCCESS : 'GET_PLAYERS_SUCCESS',
    GET_PLAYERS_FAILURE : 'GET_PLAYERS_FAILURE',
    SET_PLAYERS_STATUS_SUCCESS : 'SET_PLAYERS_STATUS_SUCCESS',
    SET_PLAYERS_CLUBS_SUCCESS : 'SET_PLAYERS_CLUBS_SUCCESS',

  }