export const auth_action_types = {
    LOGIN_SUCCESS: 'LOGIN_SUCCESS',
    LOGIN_FAILURE: 'LOGIN_FAILURE',
    LOGOUT_SUCCESS: 'LOGOUT_SUCCESS'
}
export const picksquad_action_types = {
    SET_PLAYERS_SUCCESS: 'SET_PLAYERS_SUCCESS'
}


export const manageTeam_action_types = {
    GET_MY_TEAM_SUCCESS: "GET_MY_TEAM_SUCCESS",
    SET_FIRST_SELECTED_SUCCESS: "SET_FIRST_SELECTED_SUCCESS",
    SET_NEW_TEAM_SUCCESS: "SET_NEW_TEAM_SUCCESS",
    TOGGLE_MODAL_SUCCESS: "TOGGLE_MODAL_SUCCESS",
    LOCAL_ALLOW_SUCCESS: "LOCAL_ALLOW_SUCCESS",
    GET_MY_TEAM_TRANSFER_SUCCESS: "GET_MY_TEAM_TRANSFER_SUCCESS",
    GET_TRANSFERABLE_PLAYERS_SUCCESS: "GET_TRANSFERABLE_PLAYERS_SUCCESS",
    ENABLE_TRANSFER_TABLE: "ENABLE_TRANSFER_TABLE",
    SELECT_FIRST_TRANSFER_SUCCESS : "SELECT_FIRST_TRANSFER_SUCCESS",
    SELECT_SECOND_TRANSFER_SUCCESS: "SELECT_SECOND_TRANSFER",
    ALLOWED_TO_TRANSFER_SUCCESS : "ALLOWED_TO_TRANSFER_SUCCESS",
    TRANSFER_ERROR_SUCCESS : "TRANSFER_ERROR_SUCCESS",
}


export const position = {
    GOALKEEPER: "Goalkeeper",
    DEFENDER: "Defender",
    MIDFIELDER: "Midfielder",
    FORWARD: "Forward"
}