export const ONE_PLAYER_STATISTICS = {
    PLAYER : "player",
    POINT : "point",
    NAME : "name",
    POSITION : "position",
    STATUS : "status",
    PRICE : "price",
    CLUB : "club",
    CLUB_NAME : "name",
    CLUB_IMAGE : "image",
    EVENTS : "events",
    EVENT_TYPE : "event_type",
    MATCH_ID : "match",
    EVENT_OPPONENT_NAME : "Opponent_name",
    EVENT_MINUTE : "minute",
};